### ISSUE TITLE
Fetch functions and mapping the data to types 

### ISSUE THREAD

**Issue by emilpriver** [dbcaml/dbcaml#6]
Atm do each driver map it's result to `string option list` and the idea is that we later on should be able to take a record and map fields to the fields. This is the idea of `Row.ml` file. 

Something we also need to think about when we talk about this is that if `string option` is the "correct" type or if we should rethink into returning something else and how could this if so be mapped to a type?

I did create a tiny function called `map_to` which idea was to take `string option list`and map it, however, I am not done with it yet.
The function looks like this:
```ocaml
let map_to (row : t) =
  List.fold_left
    (fun acc s ->
      match s with
      | Some v -> v :: acc
      | None -> acc)
    []
    row
```

TODO:
- [ ] Map result to a type which each fetch function use
- [ ] Implement more fetch functions
- [ ] Implement a cursors for fetch_many

**Comment by emilpriver** [comment]
I also think that the function execute which connection have should return binary. Maybe it's easier to map data then?

**Comment by leostera** [comment]
i'd love to take a stab at this one 🙏🏼

**Comment by emilpriver** [comment]
@leostera Go ahead :D

**Comment by emilpriver** [comment]
What do you think about allowing users to be able to make data from the database to a type? I had an idea of having a type as param and make the function optional to use, allow the user to select what they want to do with the data @leostera

**Comment by leostera** [comment]
So far what I'm thinking looks like this:

```ocaml
type user = { name: string; age: int }
[@deriving deserializer]

let* conn = DbCaml.connect "..." in
let* cursor = DbCaml.execute conn "select name, age from users" in
let users = Seq.map (DbCaml.of_row conn deserialize_user) user in
```

which needs the `conn` object to include a way to point to a Driver's serde format. That way each driver can have its own deserializer for its own format, so that calling `DbCaml.of_row conn` when the connection was open with the Postgres driver would be equivalent to calling `Postgres.deserialize_row`

**Comment by emilpriver** [comment]
> So far what I'm thinking looks like this:
> 
> ```ocaml
> type user = { name: string; age: int }
> [@deriving deserializer]
> 
> let* conn = DbCaml.connect "..." in
> let* cursor = DbCaml.execute conn "select name, age from users" in
> let users = Seq.map (DbCaml.of_row conn deserialize_user) user in
> ```
> 
> which needs the `conn` object to include a way to point to a Driver's serde format. That way each driver can have its own deserializer for its own format, so that calling `DbCaml.of_row conn` when the connection was open with the Postgres driver would be equivalent to calling `Postgres.deserialize_row`

I +1 this, Looks amazing. I guess we could make the `execute` function return a serde type which would bubble up to the fetch functions(which currently is: `fetch_one` `fetch_many` `exec`).

**Comment by leostera** [comment]
so serde can deserialize from any source as long as the format supports it – so in this case the driver module would provide a format module that implements whatever wire protocol the database uses.

as an example:

```ocaml
(* file: postgres.ml *)
module Wire_ser = struct
  type state = { internal state of the parser }
  (* all of the serialization functions here *)
end

module Wire_de = struct
  type state = { internal state of the parser }
  (* all of the deserialization functions here *)
end

(* file: driver.ml *)
module type Intf : sig
  module Wire_ser : Serde.Serializer.Intf
  module Wire_de : Serde.Deserializer.Intf
  (* ore things every driver needs *)
end

let make driver state = Driver (driver, state)

(* file: conn.ml *)
let execute (Conn ((module C), state)) query =
  let* stream = C.execute state query in
  Stream.map (C.Wire_de.of_bytes) stream
```

In here the `Wire_de` module defines what kind of data `C.execute` should provide it, which is convenient because both of them come from the same module, so we can make sure they match up even if every driver uses a different input data type.

**Comment by emilpriver** [comment]
> so serde can deserialize from any source as long as the format supports it – so in this case the driver module would provide a format module that implements whatever wire protocol the database uses.
> 
> as an example:
> 
> ```ocaml
> (* file: postgres.ml *)
> module Wire_ser = struct
>   type state = { internal state of the parser }
>   (* all of the serialization functions here *)
> end
> 
> module Wire_de = struct
>   type state = { internal state of the parser }
>   (* all of the deserialization functions here *)
> end
> 
> (* file: driver.ml *)
> module type Intf : sig
>   module Wire_ser : Serde.Serializer.Intf
>   module Wire_de : Serde.Deserializer.Intf
>   (* ore things every driver needs *)
> end
> 
> let make driver state = Driver (driver, state)
> 
> (* file: conn.ml *)
> let execute (Conn ((module C), state)) query =
>   let* stream = C.execute state query in
>   Stream.map (C.Wire_de.of_bytes) stream
> ```
> 
> In here the `Wire_de` module defines what kind of data `C.execute` should provide it, which is convenient because both of them come from the same module, so we can make sure they match up even if every driver uses a different input data type.

Seems neat, I will play around with it :D I feel that this is the stuff we need next in the lib

**Comment by emilpriver** [comment]
Blocked: We wait until Serde.ml is ready to be used

**Comment by emilpriver** [comment]
I'm closing this issue in favor of #20
